### ISSUE TITLE
Can't import GDAL due to deprecated import statement

### ISSUE THREAD

**Issue by troysalt** [PratyushTripathy/pyrsgis#1]
I haven't been able to import pyrsgis and I think I've tracked it down to the use of `import gdal` instead of `from osgeo import gdal`. This has been deprecated since GDAL 3.1 according to their [docs](https://gdal.org/api/python.html#imports). I also tried creating an environment with GDAL 3.0.4 to get around this, but I'm having unrelated issues.

**Comment by eusojk** [comment]
I had the same issue. 
@troysalt , how did you install gdal btw?

**Comment by troysalt** [comment]
@eusojk In regards to PyRSGIS, I think the solution for now is to install GDAL <3.1 or directly modify the function you need locally, with the correct GDAL import.

In regards to GDAL itself, I've been getting `ModuleNotFoundError: no module named '_gdal'` . I installed via Anaconda, conda-forge, and tested on two Windows and a Linux machine. I imagine it has something to do with other packages installed that cause conflicts. I can install and import GDAL in an environment with only GDAL installed, but once I add other packages (the basics, like matplotlib, numpy, scikit learn), issues usually arise.

**Comment by eusojk** [comment]
@troysalt , thanks for providing these details!

I was somehow able to have PyRSGIS work alongside GDAL 3.0.4. I tested this on Ubuntu 20.

- I first installed GDAL using conda too - but this didn't help as much as I needed to install/configure things like libssl and libcrypto. etc.
- I ended up uninstalling GDAL and reinstalling with pip instead. I followed [this](https://mothergeo-py.readthedocs.io/en/latest/development/how-to/gdal-ubuntu-pkg.html) (my python env was initially created with 3.8)

Everything seems to be working fine as of now. It sounds like you have a solution already but I thought I'll share just in case. Also, you're right that PyRSGIS should account for the deprecated imports.

**Comment by PratyushTripathy** [comment]
@troysalt About the `ModuleNotFoundError: no module named '_gdal'` error, you may find a solution [here](https://github.com/PratyushTripathy/python_gdal_automated_windows/tree/main/debugger).

**Comment by PratyushTripathy** [comment]
@troysalt I have uploaded a pre-release version with the correction. This should work now, please let me know if it doesn't work. I will close this issue in a week. You can find the pre-release version [0.4.0rc1](https://pypi.org/project/pyrsgis/0.4.0rc1/)

**Comment by PratyushTripathy** [comment]
Fixed in the recent release. Should work fine now.
